### ISSUE TITLE
Le moot dia tere ranbow pe

### ISSUE THREAD

**Issue by codewithtamim** [la-niina/moluccus-app#3]
Le moot dia tere ranbow pe

**Comment by la-niina** [comment]
what language is this ?

**Comment by codewithtamim** [comment]
> what language is this ?

Phir moot dia tere ranbow pe 🌈

**Comment by la-niina** [comment]
indradhanush mein kya gadabad hai, mainne bataaya ki main ek traansajendar mahila hoon.

**Comment by codewithtamim** [comment]
> indradhanush mein kya gadabad hai, mainne bataaya ki main ek traansajendar mahila hoon.

tor trans gandar er upre muitta dilam jah ! 😍shonar chele maia dabi kore. Bhag halar put 
🖐
